function sigDEN = func_denoise_dw1d_wibz(SIG)
% FUNC_DENOISE_DW1D Saved Denoising Process.
%   SIG: vector of data
%   -------------------
%   sigDEN: vector of denoised data

%  Auto-generated by Wavelet Toolbox on 25-May-2019 16:03:12

% Analysis parameters.
%---------------------
wname = 'db3';
level = 4;

% Denoising parameters.
%----------------------
% meth = 'rigrsure';
% scal_or_alfa = one;
sorh = 's';    % Specified soft or hard thresholding
thrSettings =  [...
    0.000082271149692 ; ...
    0.000039413619242 ; ...
    0.000126267691185 ; ...
    0.000162632666955   ...
    ];

% Denoise using CMDDENOISE.
%--------------------------
sigDEN = cmddenoise(SIG,wname,level,sorh,NaN,thrSettings);
