function sigDEN = func_denoise_dw1d(SIG)
% FUNC_DENOISE_DW1D Saved Denoising Process.
%   SIG: vector of data
%   -------------------
%   sigDEN: vector of denoised data

%  Auto-generated by Wavelet Toolbox on 25-May-2019 16:15:12

% Analysis parameters.
%---------------------
wname = 'db3';
level = 7;

% Denoising parameters.
%----------------------
% meth = 'rigrsure';
% scal_or_alfa = one;
sorh = 's';    % Specified soft or hard thresholding
thrSettings =  [...
    0.002040250703881 ; ...
    0.001792372392656 ; ...
    0.002031508045587 ; ...
    0.001584946484785 ; ...
    0.001627264202711 ; ...
    0.001810438781439 ; ...
    0.001462663244691   ...
    ];

% Denoise using CMDDENOISE.
%--------------------------
sigDEN = cmddenoise(SIG,wname,level,sorh,NaN,thrSettings);
